version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ferme
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ferme
      - DB_NAME=ferme
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  anomaly:
    build: ./anomaly_service
    depends_on:
      - db
    environment:
      - DB_NAME=ferme
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8001:8001"
    volumes:
      - ./anomaly_service:/app

  interface:
    build: ./interface_supervision
    depends_on:
      - backend
      - anomaly
    ports:
      - "8082:8082"
    volumes:
      - ./interface_supervision:/app

volumes:
  pgdata:
