# Dockerfile-simulateur
FROM python:3.11-slim

WORKDIR /app

# Dépendances
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Fichier simulateur + config
COPY simulate_loop.py .
COPY config.env .

CMD ["python", "simulate_loop.py"]
